import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "@/config/auth";
import AuthProvider from "@/provider/auth";
import { Toaster } from "react-hot-toast";
import Web3AuthProvider from "@/provider/web3-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Set up dayjs with Singapore timezone
dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault("Asia/Singapore");
dayjs.locale("en");

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getServerSession(authConfig)) as Session;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased font-inter bg-bgtext-950`}
      >
        <Web3AuthProvider>
          <AuthProvider session={session}>
            {children}
            <Toaster
              toastOptions={{
                duration: 5000,
                position: "top-center",
              }}
            />
          </AuthProvider>
        </Web3AuthProvider>
      </body>
    </html>
  );
}
